version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "123456"]
    restart: unless-stopped