services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9888:8080"
      - "50000:50000"   # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # Allow Jenkins to use host Docker daemon
      - /usr/bin/docker:/usr/bin/docker              # Docker CLI for Jenkins container
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"  # Optional: skip setup wizard (for automation)

volumes:
  jenkins_home: